version: "3"
services:
  backend:
    build: backend/
    ports:
      - 3000:3000/tcp
    volumes:
      - ./backend/:/home/dev/:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build: frontend/
    ports:
      - 80:8080/tcp
    volumes:
      - ./frontend/:/home/dev/:cached
    depends_on:
      - backend
    links:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true